// Shared merchant name to domain mapping
// Used by popup.js and background.js to match offers to merchant websites

const MERCHANT_DOMAIN_MAP = new Map(
    Object.entries({
        'banter by piercing pagoda': 'banter.com',
        'replit': 'replit.com',
        'hellofresh': 'hellofresh.com',
        'nativepath': 'nativepath.com',
        'aka hotels & residences': 'stayaka.com',
        'intimissimi': 'intimissimi.com',
        'saxx underwear': 'saxxunderwear.com',
        'litter-robot': 'litter-robot.com',
        'farmgirl flowers': 'farmgirlflowers.com',
        'event tickets center': 'eventticketscenter.com',
        'ritual': 'ritual.com',
        'the bouqs co': 'bouqs.com',
        'canon': 'canon.com',
        'lotte hotel seattle': 'lottehotel.com',
        'maurices': 'maurices.com',
        'kiwico': 'kiwico.com',
        'morgenthal frederics': 'morgenthalfrederics.com',
        'ariat': 'ariat.com',
        'express': 'express.com',
        'shiseido': 'shiseido.com',
        'grüns': 'gruns.co',
        'cozy earth': 'cozyearth.com',
        'aarp': 'aarp.org',
        'ruggable': 'ruggable.com',
        'armra': 'tryarmra.com',
        'lensdirect': 'lensdirect.com',
        'redken': 'redken.com',
        'harper wilde': 'harperwilde.com',
        'fanatics': 'fanatics.com',
        'daily harvest': 'daily-harvest.com',
        'consumer reports': 'consumerreports.org',
        'popstroke': 'popstroke.com',
        'the friendly toast': 'thefriendlytoast.com',
        'tommy john': 'tommyjohn.com',
        'straight talk': 'straighttalk.com',
        'wilson': 'wilson.com',
        'pureology': 'pureology.com',
        'green chef': 'greenchef.com',
        'fubotv': 'fubo.tv',
        'liquid iv': 'liquid-iv.com',
        'eva air': 'evaair.com',
        'air india': 'airindia.com',
        'whisker': 'whisker.com',
        'tracfone': 'tracfone.com',
        'zenni optical': 'zennioptical.com',
        'johnson fitness & wellness': 'johnsonfitness.com',
        'meta store': 'meta.com',
        'menotomy grill & tavern': 'menotomygrill.com',
        'hatch': 'hatch.co',
        'visible by verizon': 'visible.com',
        'solgaard': 'solgaard.co',
        'hp': 'hp.com',
        'thuma': 'thuma.co',
        'optimum': 'optimum.com',
        'ticketsmarter': 'ticketsmarter.com',
        'jamba juice': 'jamba.com',
        'sling tv': 'sling.com',
        'att wireless': 'att.com',
        'paramount plus': 'paramountplus.com',
        'total wireless': 'totalwireless.com',
        'the farmers dog': 'thefarmersdog.com',
        'once upon a farm': 'onceuponafarmorganics.com',
        'seatgeek': 'seatgeek.com',
        'the economist': 'economist.com',
        'lululemon': 'lululemon.com',
        'tonal': 'tonal.com',
        'elizabeth arden': 'elizabetharden.com',
        'bissell': 'bissell.com',
        'sony electronics': 'sony.com',
        'misfits market': 'misfitsmarket.com',
        'aldo': 'aldoshoes.com',
        'viator': 'viator.com',
        'blue apron': 'blueapron.com',
        'fragrance.com': 'fragrance.com',
        'iherb': 'iherb.com',
        'dropbox': 'dropbox.com',
        'cookunity': 'cookunity.com',
        'nordictrack': 'nordictrack.com',
        'ancestry': 'ancestry.com',
        'kohler': 'kohler.com',
        'wild alaskan company': 'wildalaskancompany.com',
        'turbotax': 'turbotax.intuit.com',
        'prenuvo': 'prenuvo.com',
        'ag1': 'drinkag1.com',
        'calm': 'calm.com',
        'true religion': 'truereligion.com',
        'trust & will': 'trustandwill.com',
        'prettylitter': 'prettylitter.com',
        'grown brilliance': 'grownbrilliance.com',
        'onnit': 'onnit.com',
        'glassesusa': 'glassesusa.com',
        'therabody': 'therabody.com',
        'tory burch': 'toryburch.com',
        'youtube tv': 'tv.youtube.com',
        'home chef': 'homechef.com',
        'smashburger': 'smashburger.com',
        'airalo': 'airalo.com',
        'brilliant earth': 'brilliantearth.com',
        'the vitamin shoppe': 'vitaminshoppe.com',
        'oxo': 'oxo.com',
        'bloomsybox': 'bloomsybox.com',
        'turo': 'turo.com',
        'rugs usa': 'rugsusa.com',
        'olaplex': 'olaplex.com',
        'h&r block': 'hrblock.com',
        'lg': 'lg.com',
        'expedia amex': 'expedia.com',
        'briggs & riley': 'briggs-riley.com',
        'sweetwater': 'sweetwater.com',
        'pura': 'pura.com',
        'nobull': 'nobullproject.com',
        'natori': 'natori.com',
        'gorjana': 'gorjana.com',
        'burberry': 'burberry.com',
        'staud': 'staud.clothing',
        'cnn': 'cnn.com',
        'zagg': 'zagg.com',
        'branch basics': 'branchbasics.com',
        'bed bath & beyond': 'bedbathandbeyond.com',
        'newegg': 'newegg.com',
        'bonobos': 'bonobos.com',
        'southern tide': 'southerntide.com',
        'gametime': 'gametime.co',
        'cotopaxi': 'cotopaxi.com',
        'gainful': 'gainful.com',
        'factor': 'factor75.com',
        'mizzen+main': 'mizzenandmain.com',
        'teleflora': 'teleflora.com',
        'guardian bikes': 'guardianbikes.com',
        'fair harbor': 'fairharborclothing.com',
        'jared': 'jared.com',
        'peak design': 'peakdesign.com',
        'purple': 'purple.com',
        'maui jim': 'mauijim.com',
        'qdoba': 'qdoba.com',
        'the motley fool': 'fool.com',
        'away': 'awaytravel.com',
        'contacts direct': 'contactsdirect.com',
        'eyebuydirect': 'eyebuydirect.com',
        'steve madden': 'stevemadden.com',
        'rag & bone': 'rag-bone.com',
        'simplehuman': 'simplehuman.com',
        '1-800-flowers': '1800flowers.com',
        'betterhelp': 'betterhelp.com',
        'stretchlab': 'stretchlab.com',
        'biossance': 'biossance.com',
        'quickbooks': 'quickbooks.intuit.com',
        'simple tire': 'simpletire.com',
        'mackage': 'mackage.com',
        'office supply': 'officesupply.com',
        'the atlantic': 'theatlantic.com',
        'versace': 'versace.com',
        'faherty': 'fahertybrand.com',
        'negative underwear': 'negativeunderwear.com',
        'levis': 'levi.com',
        'tommy hilfiger': 'tommy.com',
        'hbo max': 'max.com',
        'zwilling': 'zwilling.com',
        'walmart plus': 'walmart.com',
        'discovery plus': 'discoveryplus.com',
        'tulum mexican cuisine': 'tulummexicancuisine.com',
        'paramount+': 'paramountplus.com',
        'solea restaurant and tapas bar': 'solearestaurant.com',
        'pizzeria enzina': 'enzinadc.com',
        'cafe saint germain': 'cafesaintgermain.com',
        'tremonte restaurant and bar': 'tremonterestaurant.com',
        'the fat greek': 'thefatgreekdc.com',
        'love at first bite thai kitchen': 'loveatfirstbitethai.com',
        'mamaleh\'s delicatessen': 'mamalehs.com',
        'what a soup': 'whatasoup.com',
        'circle k in-store': 'circlek.com',
        'onnit labs': 'onnit.com',
        'liquid i.v.': 'liquid-iv.com',
        'kipling': 'kipling-usa.com',
        'nuts.com': 'nuts.com',
        'prettylitter cat litter': 'prettylitter.com',
        'forme': 'forme.life',
        'lands\' end': 'landsend.com',
        'the farmer\'s dog': 'thefarmersdog.com',
        'just salad': 'justsalad.com'
    })
);

// Helper function to get domain for a merchant name
function getMerchantDomain(merchant) {
    if (!merchant) return null;

    // First check if it's already a URL pattern (e.g., "expedia.com")
    const urlPattern = /^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$/;
    if (urlPattern.test(merchant.trim())) {
        return merchant.toLowerCase().replace(/^www\./, '');
    }

    // Look up in merchant mapping (case-insensitive)
    const normalizedName = merchant.toLowerCase().trim();
    return MERCHANT_DOMAIN_MAP.get(normalizedName) || null;
}

// Export for use in other scripts
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { MERCHANT_DOMAIN_MAP, getMerchantDomain };
}
